### ISSUE TITLE
Don't seem to be able to install the add on in Blender 2.72 and 2.74

### ISSUE THREAD

**Issue by IXK** [gethiox/GXAudioVisualisation#5]
Just as the title says... Can't install it. Also tried to simply copy the file in the addon folder but didn't work either.
Apart from that, kudos for volunteering to make such a script/addon for free. Can't support this with a donation, but I wish I could. However, you might just get a praise-email from me. I really appreciate coders and in general people who make open source stuff for the greater good of everybody.
Greets.\
IK

**Comment by gethiox** [comment]
yeah, write opensource software is a really expensive business for me. It is my time, nobody pay me for it actually.
Did you get any messages/errors after try to install script?
Btw [here](https://github.com/gethiox/GXAudioVisualisation/wiki/Addon-Instalation) is a little instalation guide

**Comment by IXK** [comment]
I'm sorry I can't support you with a donation my friend. Really. I'm just a broke music maker lol
I saw the install guide . And no, it did not show any error message, or at least I didn't see it... just gettin started in to this blender thing again as I wanna do videos for my music and remixes.
If you could take a look at the issue when you have time, I'd be thankful . Until then though, I think I'll just try to code from scratch as much as I can.
Greetings.
IK

**Comment by gethiox** [comment]
Easy bro, I understand, donations are voluntary :)
Well, I really don't know what happend, script works for me on blender 2.73a, and even 2.69.
Script are visible in Add-ons in User category?

**Comment by IXK** [comment]
Yep. It does not show under 'user' category or anywhere.
I think I'll try to install 2.73a or / and 2.69 and see what's up.
Thanks for the prompt answers by the way. Greatly appreciated.
IK

**Comment by gethiox** [comment]
At first try to copy the whole script and paste it into blender-text-editor, then press "Run" and check if addon appear in scene tab.

If not… 
Are you using Windows or Linux? Maybe blender give some errors on console.
Try to watch blender-console while installing addon in normal way, It is above information bar (bar on the top of blender) - you can easily grab his edge and pull down, console space will be visible now.
![15 03 2015r-23 56 27s-border](https://cloud.githubusercontent.com/assets/1618352/6658605/ec17072a-cb6e-11e4-9346-db6281045541.png)

If nothing special appear here after addon install, you need to check system console.
In linux you just need to run blender in terminal, In windows I don't know - the same way to run blender in cmd, I think.

It is weird, but it isn't surprise - quality of my code are bad, very bad I think.

**Comment by IXK** [comment]
Dude. I'm sorry it's been my mistake... After trying things for a while I found out that even though I saw the 'Install' directions, I didn't download it correctly. So basically I had downloaded an html page instead. My apologies for wasting your time. Now I'm trying it out. So far everything works as described by your self in the use manual.
Thanks. And my apologies again.

**Comment by gethiox** [comment]
Hah :D
Mistakes happen. I am glad that the problem has been solved. :)
