### ISSUE TITLE
Crashes [not responding window under Windows system]

### ISSUE THREAD

**Issue by brandleesee** [gethiox/GXAudioVisualisation#6]
After I click **(re)Bake animation data** Blender crashes. Maximum time I waited was 15 minutes and had to close Blender by the End Process dialog. This happens every time I press that button.

Installation of plugin was successful.
Blender 2.76b
Windows 7

**Comment by gethiox** [comment]
I will check it.
After you press that button, blender immediately freezes or cursor changed to percentage progress?
Do you use default panel-plugin values or you increase these? If true, maybe it generate too much data and your PC are out of RAM. (but I don't think so)

Also try to provide blender crash output:
run blender by windows terminal <win>+<r>, type "cmd" and press Enter, go to directory with blender by "cd" command (and Tab key for auto-completion folders name), eg "cd Downloads", "cd blender-2.76b-windows64", and then run blender by typing "blender.exe". After crash just select all in terminal (RMB > select all), and copy (<Enter>)

**Comment by brandleesee** [comment]
Hello again, the cursor changes to a small black box with the percentage, however, on clicking anywhere, Blender just freezes. After minutes, it unfreezes.

One point to note is that the 15 minutes period I mentioned, happened that one time only.

I tested and worked with the script for a whole day and actually managed to produce my intended project. Thus, I ask if some kind of popup can be created with a sequence bar that does not freeze (Not Responding) Blender but does not allow the user to interact with the program until the baking is done and ready. This way one would know that Blender is still functioning.

**Comment by mark-spurgeon** [comment]
Hi, this might be because you're using an mp3 sound file. It does this with me. It should work with .wav files though

**Comment by gethiox** [comment]
@brandleesee yeah, it is an issue under windows systems where UI is not responding when baking process is in progress and windows decide to tell the user that blender is not responding anymore (which is true in fact because baking blocks UI process).
I was trying to fix that some time ago but without effect, I will try to fix that in the planned new version of my plugin (or at lesat inform user about possible window freezing under windows).

**Comment by brandleesee** [comment]
Is version 2 still happenning?

**Comment by gethiox** [comment]
@brandleesee Nothing is actively happening at the moment.

**Comment by brandleesee** [comment]
Closing as this issue is 3.5 years old. Also, code might need a revamp due to newer versions of Blender.
